//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//



jQuery.r3Utils.namespace("org.r3.db.sailevent.entrylist");

org.r3.db.sailevent.entrylist.SailEntryListDTO = Class.extend(
{
	 init: function(aDataBean)
	 {  
	 	 	 this.dtrowclass   = "grade_sailentrylist";
       this.dtokey       = aDataBean.dtokey   || null;
       this.dtodescr     = aDataBean.dtodescr || null;
       
        this.eventid = aDataBean.eventid || null;
        this.applicationid = aDataBean.applicationid || null;
        this.userid = aDataBean.userid || null;
        this.verificationstatus = aDataBean.verificationstatus || null;
        this.plate = aDataBean.plate || null;
        this.sailnumber = aDataBean.sailnumber || null;
        this.yachtname = aDataBean.yachtname || null;
        this.yachtclub = aDataBean.yachtclub || null;
        this.yachttype = aDataBean.yachttype || null;
        this.yachtbsf = aDataBean.yachtbsf || null;
        this.yachtgph = aDataBean.yachtgph || null;
        this.racegroup = aDataBean.racegroup || null;
        this.raceclass = aDataBean.raceclass || null;
        this.apptype = aDataBean.apptype || null;
        this.boatimageurl = aDataBean.boatimageurl || null;
        this.boatimageheight = aDataBean.boatimageheight || null;
        this.boatimagewidth = aDataBean.boatimagewidth || null;
        this.boaticonurl = aDataBean.boaticonurl || null;
        this.boaticonwidth = aDataBean.boaticonwidth || null;
        this.boaticonheight = aDataBean.boaticonheight || null;
        this.ownerfirstname = aDataBean.ownerfirstname || null;
        this.ownerlastname = aDataBean.ownerlastname || null;
        this.owneremail = aDataBean.owneremail || null;
        this.ownercellphone = aDataBean.ownercellphone || null;
        this.accepted = aDataBean.accepted || null;
 
	 }
    
   
});
