//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//


package org.r3.db.system.siteview;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SiteViewMapper{    
  List<org.r3.db.system.siteview.SiteViewDTO> select(
            @Param("filter") org.r3.db.system.siteview.SiteViewFilter filterCondition, 
            @Param("pcfg")   org.r3.db.PersistenceConfigInfo pcfg,
            RowBounds aRowBounds);
            
  int count(@Param("filter") org.r3.db.system.siteview.SiteViewFilter aFilterCondition,
            @Param("pcfg")   org.r3.db.PersistenceConfigInfo pcfg);
            
  List<org.r3.db.system.site.SiteDTO> selectSiteDTO(
          @Param("filter") org.r3.db.system.siteview.SiteViewFilter filterCondition, 
          @Param("pcfg")   org.r3.db.PersistenceConfigInfo pcfg,
          RowBounds aRowBounds);     
}
  
