//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//


package org.r3.db.system.site;

public class SiteKey
{
    protected java.lang.String  site;


    /**
      * DataBean constructor.
      */
    public SiteKey() 
    {    
    }
    
    /**
      * Copy constructor.
      */    
    public SiteKey(SiteKey another) 
    {    	
       site = another.getSite();
    }
       
    /**
      * DataBean Getter And Setter Accessor
      */    
    
    public java.lang.String   getSite()         { return site; }
    
    public void setSite(String  p)
    {
         site = p;
    }
}
