//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//


package org.r3.db.system.metadata.tmetadataview;

public class TableColumnsMetadataPersistence extends TableColumnsMetadataPersistenceBase
{
  public static TableColumnsMetadataPersistence createPersistenceObject(org.r3.db.PersistenceContext pcfg, org.apache.ibatis.session.SqlSession aSession)
	{
		  TableColumnsMetadataPersistence p = new TableColumnsMetadataPersistence();
	    p.setMapper(aSession.getMapper(TableColumnsMetadataMapper.class));
	    return p;
  }    

}
  
