//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//


package org.r3.db.system.metadata.tmetadataview;

import org.r3.db.utils.DTOCSVStreamingOutput;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.util.List;

import javax.ws.rs.WebApplicationException;

public class TableColumnsMetadataCSVStreamingOutput extends DTOCSVStreamingOutput
{
    private java.util.List<TableColumnsMetadataDTO> listOfDTOs;
    
    public TableColumnsMetadataCSVStreamingOutput(List<TableColumnsMetadataDTO> aListOfDTOs)
    {
        super(TableColumnsMetadataDTO.class);
    	  listOfDTOs = aListOfDTOs;
    }
        
	  public void write(OutputStream arg0) throws IOException, WebApplicationException
	  {
        PrintWriter prt = new PrintWriter(new OutputStreamWriter(arg0, "UTF-8"));
		    printlnHeader(prt);
		
				if (listOfDTOs != null)
				{
					for(TableColumnsMetadataDTO dto : listOfDTOs)
					{
						println(prt, dto);
					}
				}
				
				prt.flush();
		}

}
