//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//


package org.r3.db.system.metadata.tmetadataview;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TableColumnsMetadataMapper{    
  List<org.r3.db.system.metadata.tmetadataview.TableColumnsMetadataDTO> select(
            @Param("filter") org.r3.db.system.metadata.tmetadataview.TableColumnsMetadataFilter filterCondition, 
            @Param("pcfg")   org.r3.db.PersistenceConfigInfo pcfg,
            RowBounds aRowBounds);
            
  int count(@Param("filter") org.r3.db.system.metadata.tmetadataview.TableColumnsMetadataFilter aFilterCondition,
            @Param("pcfg")   org.r3.db.PersistenceConfigInfo pcfg);
            
}
  
