//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//


package org.r3.db.system.metadata.tmetadataview;

import java.util.List;
import java.util.ArrayList;

public class TableColumnsMetadataFilter{
    protected String orderByClause;
    protected String  groupByClause;
    protected boolean distinct;
    protected int     limitFetch;
    
    protected List<org.r3.db.utils.Criteria> oredCriteria;

    public TableColumnsMetadataFilter() 
    {
        oredCriteria = new ArrayList<org.r3.db.utils.Criteria>();
        limitFetch = 0;
        groupByClause = null;
    }
    
    public String getGroupByClause()
	  {
	  	return groupByClause;
	  }
    
	  public void setGroupByClause(String groupByClause)
	  {
	  	this.groupByClause = groupByClause;
	  }
	
	  public boolean isGroupBy(String aColumnName)
	  {
	  	return groupByClause != null && groupByClause.indexOf(aColumnName) >= 0;
	  }
	
    public void setOrderByClause(String orderByClause) 
    {
        this.orderByClause = orderByClause;
    }
    
    public String getOrderByClause() 
    {
        return orderByClause;
    }

    public int getLimitFetch()
  	{
		   return limitFetch;
	  }

	  public void setLimitFetch(int limitFetch)
	  {
		  this.limitFetch = limitFetch;
	  }

    public void setDistinct(boolean distinct) 
    {
        this.distinct = distinct;
    }

    public boolean isDistinct() 
    {
        return distinct;
    }

    public List<org.r3.db.utils.Criteria> getOredCriteria() 
    {
        return oredCriteria;
    }

    public void or(org.r3.db.utils.Criteria criteria) 
    {
        oredCriteria.add(criteria);
    }

    public TableColumnsMetadataCriteria or() 
    {
        TableColumnsMetadataCriteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public TableColumnsMetadataCriteria createCriteria() 
    {
        TableColumnsMetadataCriteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected TableColumnsMetadataCriteria createCriteriaInternal() 
    {
        TableColumnsMetadataCriteria criteria = new TableColumnsMetadataCriteria();
        return criteria;
    }

    public void clear() 
    {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public static abstract class TableColumnsMetadataCriteriaBase extends org.r3.db.utils.Criteria
    {
        
        public TableColumnsMetadataCriteria andTable_schemaIsNull() {
            addCriterion("table_schema is null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_schemaIsNotNull() {
            addCriterion("table_schema is not null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_schemaEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("table_schema =", value, "table_schema");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_schemaNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("table_schema <>", value, "table_schema");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_schemaGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("table_schema >", value, "table_schema");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_schemaGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("table_schema >=", value, "table_schema");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_schemaLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("table_schema <", value, "table_schema");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_schemaLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("table_schema <=", value, "table_schema");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_schemaLike(java.lang.String value) {
            if (value != null)
              addCriterion("table_schema like ", value, "table_schema");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_schemaNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("table_schema not like ", value, "table_schema");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_schemaIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("table_schema in ", value, "table_schema");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_schemaNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("table_schema not in ", value, "table_schema");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_schemaBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("table_schema between ", value1, value2, "table_schema");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_schemaNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("table_schema not between ", value1, value2, "table_schema");
            return (TableColumnsMetadataCriteria) this;
        }
        
        public TableColumnsMetadataCriteria andTable_nameIsNull() {
            addCriterion("table_name is null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_nameIsNotNull() {
            addCriterion("table_name is not null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_nameEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("table_name =", value, "table_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_nameNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("table_name <>", value, "table_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_nameGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("table_name >", value, "table_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_nameGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("table_name >=", value, "table_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_nameLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("table_name <", value, "table_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_nameLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("table_name <=", value, "table_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_nameLike(java.lang.String value) {
            if (value != null)
              addCriterion("table_name like ", value, "table_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_nameNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("table_name not like ", value, "table_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_nameIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("table_name in ", value, "table_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_nameNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("table_name not in ", value, "table_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_nameBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("table_name between ", value1, value2, "table_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andTable_nameNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("table_name not between ", value1, value2, "table_name");
            return (TableColumnsMetadataCriteria) this;
        }
        
        public TableColumnsMetadataCriteria andColumn_nameIsNull() {
            addCriterion("column_name is null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andColumn_nameIsNotNull() {
            addCriterion("column_name is not null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andColumn_nameEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("column_name =", value, "column_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andColumn_nameNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("column_name <>", value, "column_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andColumn_nameGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("column_name >", value, "column_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andColumn_nameGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("column_name >=", value, "column_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andColumn_nameLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("column_name <", value, "column_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andColumn_nameLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("column_name <=", value, "column_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andColumn_nameLike(java.lang.String value) {
            if (value != null)
              addCriterion("column_name like ", value, "column_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andColumn_nameNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("column_name not like ", value, "column_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andColumn_nameIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("column_name in ", value, "column_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andColumn_nameNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("column_name not in ", value, "column_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andColumn_nameBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("column_name between ", value1, value2, "column_name");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andColumn_nameNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("column_name not between ", value1, value2, "column_name");
            return (TableColumnsMetadataCriteria) this;
        }
        
        public TableColumnsMetadataCriteria andOrdinal_positionIsNull() {
            addCriterion("ordinal_position is null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andOrdinal_positionIsNotNull() {
            addCriterion("ordinal_position is not null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andOrdinal_positionEqualTo(java.lang.Long value) {
            if (value != null)
              addCriterion("ordinal_position =", value, "ordinal_position");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andOrdinal_positionNotEqualTo(java.lang.Long value) {
            if (value != null)
              addCriterion("ordinal_position <>", value, "ordinal_position");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andOrdinal_positionGreaterThan(java.lang.Long value) {
            if (value != null)
              addCriterion("ordinal_position >", value, "ordinal_position");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andOrdinal_positionGreaterThanOrEqualTo(java.lang.Long value) {
            if (value != null)
              addCriterion("ordinal_position >=", value, "ordinal_position");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andOrdinal_positionLessThan(java.lang.Long value) {
            if (value != null)
              addCriterion("ordinal_position <", value, "ordinal_position");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andOrdinal_positionLessThanOrEqualTo(java.lang.Long value) {
            if (value != null)
              addCriterion("ordinal_position <=", value, "ordinal_position");
            return (TableColumnsMetadataCriteria) this;
        }

        
        public TableColumnsMetadataCriteria andNullableIsNull() {
            addCriterion("nullable is null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andNullableIsNotNull() {
            addCriterion("nullable is not null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andNullableEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("nullable =", value, "nullable");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andNullableNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("nullable <>", value, "nullable");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andNullableGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("nullable >", value, "nullable");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andNullableGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("nullable >=", value, "nullable");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andNullableLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("nullable <", value, "nullable");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andNullableLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("nullable <=", value, "nullable");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andNullableLike(java.lang.String value) {
            if (value != null)
              addCriterion("nullable like ", value, "nullable");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andNullableNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("nullable not like ", value, "nullable");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andNullableIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("nullable in ", value, "nullable");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andNullableNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("nullable not in ", value, "nullable");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andNullableBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("nullable between ", value1, value2, "nullable");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andNullableNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("nullable not between ", value1, value2, "nullable");
            return (TableColumnsMetadataCriteria) this;
        }
        
        public TableColumnsMetadataCriteria andData_typeIsNull() {
            addCriterion("data_type is null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_typeIsNotNull() {
            addCriterion("data_type is not null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_typeEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("data_type =", value, "data_type");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_typeNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("data_type <>", value, "data_type");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_typeGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("data_type >", value, "data_type");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_typeGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("data_type >=", value, "data_type");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_typeLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("data_type <", value, "data_type");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_typeLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("data_type <=", value, "data_type");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_typeLike(java.lang.String value) {
            if (value != null)
              addCriterion("data_type like ", value, "data_type");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_typeNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("data_type not like ", value, "data_type");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_typeIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("data_type in ", value, "data_type");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_typeNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("data_type not in ", value, "data_type");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_typeBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("data_type between ", value1, value2, "data_type");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_typeNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("data_type not between ", value1, value2, "data_type");
            return (TableColumnsMetadataCriteria) this;
        }
        
        public TableColumnsMetadataCriteria andData_lengthIsNull() {
            addCriterion("data_length is null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_lengthIsNotNull() {
            addCriterion("data_length is not null");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_lengthEqualTo(java.lang.Long value) {
            if (value != null)
              addCriterion("data_length =", value, "data_length");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_lengthNotEqualTo(java.lang.Long value) {
            if (value != null)
              addCriterion("data_length <>", value, "data_length");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_lengthGreaterThan(java.lang.Long value) {
            if (value != null)
              addCriterion("data_length >", value, "data_length");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_lengthGreaterThanOrEqualTo(java.lang.Long value) {
            if (value != null)
              addCriterion("data_length >=", value, "data_length");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_lengthLessThan(java.lang.Long value) {
            if (value != null)
              addCriterion("data_length <", value, "data_length");
            return (TableColumnsMetadataCriteria) this;
        }
        public TableColumnsMetadataCriteria andData_lengthLessThanOrEqualTo(java.lang.Long value) {
            if (value != null)
              addCriterion("data_length <=", value, "data_length");
            return (TableColumnsMetadataCriteria) this;
        }

    }
    
}

