//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//


package org.r3.db.system.metadata.tmetadataview;
import org.r3.db.utils.*;
import java.util.List;
import java.util.ArrayList;

public class TableColumnsMetadataCriteria extends TableColumnsMetadataFilter.TableColumnsMetadataCriteriaBase{
}
