//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//


package org.r3.db.sailevent.attendancesheetview;

import org.r3.db.DTOBase;

public class SailAttendanceSheetViewDTO extends SailAttendanceSheetViewDTOBase
{
    public SailAttendanceSheetViewDTO()
    {
        super();
    }

    public SailAttendanceSheetViewDTO(SailAttendanceSheetViewDTO another)
    {
        super(another);
    }

    public String getAttendanceyesAsYESNO()
    {
    	String s = getAttendanceyes();
    	return s != null && s.equalsIgnoreCase("btrue") ? "SI" : "NO";
    }
    
    public String getCrewregularAsYESNO()
    {
    	String s = getCrewregular();
    	return s != null && s.equalsIgnoreCase("btrue") ? "SI" : "NO";
    }
    
}
