//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//



jQuery.r3Utils.namespace("org.r3.db.sailevent.appcrewmemberview");

org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewDTO = Class.extend(
{
	 init: function(aDataBean)
	 {  
	 	 	 this.dtrowclass   = "grade_sailapplicationcrewmemberview";
       this.dtokey       = aDataBean.dtokey   || null;
       this.dtodescr     = aDataBean.dtodescr || null;
       
        this.crewmemberid = aDataBean.crewmemberid || null;
        this.eventid = aDataBean.eventid || null;
        this.applicationid = aDataBean.applicationid || null;
        this.cardnumber = aDataBean.cardnumber || null;
        this.crewmembername = aDataBean.crewmembername || null;
        this.weight = aDataBean.weight || null;
        this.crewmemberrolecode = aDataBean.crewmemberrolecode || null;
        this.memberstatuscode = aDataBean.memberstatuscode || null;
        this.createtimestamp = aDataBean.createtimestamp || null;
        this.deletetimestamp = aDataBean.deletetimestamp || null;
        this.checkcardnumber = aDataBean.checkcardnumber || null;
        this.checkcardnumber_ts = aDataBean.checkcardnumber_ts || null;
        this.recstatus = aDataBean.recstatus || null;
        this.rectimestamp = aDataBean.rectimestamp || null;
        this.cardnumberstatuscode = aDataBean.cardnumberstatuscode || null;
        this.yachtclub = aDataBean.yachtclub || null;
        this.cardholdername = aDataBean.cardholdername || null;
        this.cardholderlastname = aDataBean.cardholderlastname || null;
        this.medexamexpirationdate = aDataBean.medexamexpirationdate || null;
        this.cardexpirationdate = aDataBean.cardexpirationdate || null;
        this.renewaldate = aDataBean.renewaldate || null;
        this.generalcardexpirationdate = aDataBean.generalcardexpirationdate || null;
        this.systemcheckdate = aDataBean.systemcheckdate || null;
        this.sailnumber = aDataBean.sailnumber || null;
        this.yachtname = aDataBean.yachtname || null;
        this.completionstatus = aDataBean.completionstatus || null;
        this.verificationstatus = aDataBean.verificationstatus || null;
        this.numcoviddocs = aDataBean.numcoviddocs || null;
 
	 }
    
  ,compareTo: function(anItemId)
   {
   	   if (!this.dtokey)
   	       return -99;
   	       
   	   if (this.dtokey < anItemId)
   	       return -1;
   	   else if (this.dtokey > anItemId)
   	   	   return  1;
   	   	   
   	   return 0;
   }
   
});
