//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//


package org.r3.db.system.eventlog;

public class EventLogKey
{
    protected java.lang.Integer  eventid;


    /**
      * DataBean constructor.
      */
    public EventLogKey() 
    {    
    }
    
    /**
      * Copy constructor.
      */    
    public EventLogKey(EventLogKey another) 
    {    	
       eventid = another.getEventid();
    }
       
    /**
      * DataBean Getter And Setter Accessor
      */    
    
    public java.lang.Integer   getEventid() { return eventid; }
    
    public void setEventid(java.lang.Integer  p)
    {
    	eventid = p;
    }
    public void setEventid(int p)
    {
    	setEventid(new java.lang.Integer(p));
    }
    public void setEventid()
    {
    	setEventid(0);
    }
}
