cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3                                           & ren     Messages.json.pt                           Messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\console\bbs                               & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\console\cms\cards                         & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\console\contacts                          & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\console\home                              & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\console\home\itilsite                     & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\home\yachtclubsite                   & ren     messages_en.json                           messages.js.en                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\console\regattas                          & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\console\siteconfig                        & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\console\siteconfig\page                   & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\console\siteconfig\site                   & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\console\tow                               & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\console\users                             & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\console\wbs                               & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\actor\actor                            & ren     ActorDictionary.json.pt                    ActorDictionary.js.pt                    
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\actor\group                            & ren     ActorGroupDictionary.json.pt               ActorGroupDictionary.js.pt               
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\bbs\bbsthread                          & ren     BBSThreadDictionary.json.pt                BBSThreadDictionary.js.pt               
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\bbs\bbsthreadnode                      & ren     BBSThreadNodeDictionary.json.pt            BBSThreadNodeDictionary.js.pt           
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\bbs\bbsthreadnodeview                  & ren     BBSThreadNodeViewDictionary.json.pt        BBSThreadNodeViewDictionary.js.pt       
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\bbs\bbstopic                           & ren     BBSTopicDictionary.json.pt                 BBSTopicDictionary.js.pt                
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\bbs\bbstopicview                       & ren     BBSTopicViewDictionary.json.pt             BBSTopicViewDictionary.js.pt            
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\cms\card                               & ren     CardDictionary.json.pt                     CardDictionary.js.pt                        
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\cms\carddescr                          & ren     CardDescrDictionary.json.pt                CardDescrDictionary.js.pt               
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\cms\cardproperty                       & ren     CardPropertyDictionary.json.pt             CardPropertyDictionary.js.pt            
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\cms\page                               & ren     PageDictionary.json.pt                     PageDictionary.js.pt                        
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\cms\pagedescr                          & ren     PageDescrDictionary.json.pt                PageDescrDictionary.js.pt               
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\project\siteresource                   & ren     SiteResourceDictionary.json.pt             SiteResourceDictionary.js.pt            
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\system\fileimport\fileimport           & ren     FileImportDictionary.json.pt               FileImportDictionary.js.pt              
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\system\site                            & ren     SiteDictionary.json.pt                     SiteDictionary.js.pt                     
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\system\smsqueue                        & ren     SMSQueueDictionary.json.pt                 SMSQueueDictionary.js.pt                
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\system\user\user                       & ren     UserDictionary.json.pt                     UserDictionary.js.pt                    
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\wbs\wbs                                & ren     WBSDictionary.json.pt                      WBSDictionary.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\db\wbs\wbsnode                            & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\home\mastersite                           & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\bbs                             & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\changeuserpwd                   & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\cmsconsole                      & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\fileupload                      & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\mongocms                        & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\outmail                         & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\project\siteresource            & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\registration                    & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\resetuserpwd                    & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\timeline                        & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\user                            & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\wbs                             & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\wbs\dashboard                   & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\jsportlet\wbs\mytodolist                  & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\registration                              & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\wbs\wbsfillout                            & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent\org\r3\wbs\wsreport                              & ren     messages.json.pt                           messages.js.pt                          
cd E:\home\projects\regattacubed_bs7\r3ng\WebContent
