//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//



jQuery.r3Utils.namespace("org.r3.db.sailevent.appdocument");

org.r3.db.sailevent.appdocument.SailApplicationDocumentDTO = Class.extend(
{
	 init: function(aDataBean)
	 {  
	 	 	 this.dtrowclass   = "grade_sailapplicationdocument";
       this.dtokey       = aDataBean.dtokey   || null;
       this.dtodescr     = aDataBean.dtodescr || null;
       
        this.documentid = aDataBean.documentid || null;
        this.eventid = aDataBean.eventid || null;
        this.applicationid = aDataBean.applicationid || null;
        this.documenttypecode = aDataBean.documenttypecode || null;
        this.documentname = aDataBean.documentname || null;
        this.documenturl = aDataBean.documenturl || null;
        this.filesize = aDataBean.filesize || null;
        this.contenttype = aDataBean.contenttype || null;
        this.annotation = aDataBean.annotation || null;
        this.imageurl = aDataBean.imageurl || null;
        this.imageheight = aDataBean.imageheight || null;
        this.imagewidth = aDataBean.imagewidth || null;
        this.iconurl = aDataBean.iconurl || null;
        this.iconwidth = aDataBean.iconwidth || null;
        this.iconheight = aDataBean.iconheight || null;
        this.uploadtimestamp = aDataBean.uploadtimestamp || null;
        this.crewmemberid = aDataBean.crewmemberid || null;
 
	 }
    
  ,compareTo: function(anItemId)
   {
   	   if (!this.dtokey)
   	       return -99;
   	       
   	   if (this.dtokey < anItemId)
   	       return -1;
   	   else if (this.dtokey > anItemId)
   	   	   return  1;
   	   	   
   	   return 0;
   }
   
});
