//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//



package org.r3.db.sailevent.appcrewmemberview;


import java.util.List;
import org.apache.ibatis.session.RowBounds;

public class SailApplicationCrewMemberViewPersistenceBase
{
  protected SailApplicationCrewMemberViewMapper mapper;
  
  public void setMapper(SailApplicationCrewMemberViewMapper aMapper)
  {
     this.mapper = aMapper;
  }
  
  public SailApplicationCrewMemberViewPersistenceBase ()
  {
  
  }

  public org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewDTO selectFirst(org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewFilter filterCondition, org.r3.db.PersistenceConfigInfo pcfg)
  {   
      if (filterCondition == null)
      {
         filterCondition = new org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewFilter();
      }
      filterCondition.setLimitFetch(1);

      List<org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewDTO> l = select(filterCondition, pcfg, new RowBounds(0, 1));
      if (l != null && l.size() > 0)
     			return l.get(0);
     			
      return null;
  }
      
  public List<org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewDTO> select(org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewFilter filterCondition, org.r3.db.PersistenceConfigInfo pcfg)
  {      
      return select(filterCondition, pcfg, null);
  }

  public List<org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewDTO> select(org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewFilter filterCondition, org.r3.db.PersistenceConfigInfo pcfg, RowBounds aRowBounds)
  {      
      if (filterCondition == null)
      {
         filterCondition = new org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewFilter();
      }
            
      if (aRowBounds == null)
         aRowBounds = new RowBounds();
      else
      {      
    	   if (aRowBounds.getLimit() < RowBounds.NO_ROW_LIMIT)
              filterCondition.setLimitFetch(aRowBounds.getOffset() + aRowBounds.getLimit());
      }
                              
      List<org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewDTO> listOfDTOs = this.mapper.select(filterCondition, pcfg, aRowBounds);
      return listOfDTOs;
  }
  
  public int count(org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewFilter aFilterCondition, org.r3.db.PersistenceConfigInfo pcfg)
  {
      int numberOfRowsAffected = this.mapper.count(aFilterCondition, pcfg);
      return numberOfRowsAffected;  
  }

  public org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewDataTableAdapter query(
      org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewFilter aFilterCondition, 
      org.r3.db.PersistenceConfigInfo pcfg, 
      String sEcho, 
      int iDisplayStart, 
      int iDisplayLength,
      boolean countElements)
  {  
    	int numberOfItems = (countElements) ? count(aFilterCondition, pcfg) : -1;    	
    	List<org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewDTO> l = null;
    	if (numberOfItems != 0)
    	{
    	RowBounds rb = new RowBounds(
    					(iDisplayStart >= 0)  ? iDisplayStart : RowBounds.NO_ROW_OFFSET, 
    			    (iDisplayLength > 0) ? iDisplayLength : RowBounds.NO_ROW_LIMIT);
    	    	
		  l = select(aFilterCondition, pcfg, rb);
      }
      
		  org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewDataTableAdapter dt = new org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewDataTableAdapter();
		  dt.setsEcho(sEcho);
		  if (numberOfItems >= 0)
		  {
		     dt.setiTotalRecords(numberOfItems);
		     dt.setiTotalDisplayRecords(numberOfItems);
		  }
		  else
		  {
		     if (l != null)
		     {
		     dt.setiTotalRecords(l.size());
		     dt.setiTotalDisplayRecords(l.size());
		     }
		     else
		     {
		     dt.setiTotalRecords(0);
		     dt.setiTotalDisplayRecords(0);
		     }
		  }
		  dt.setAaData(l);
		
		  return dt;
  }  

  public org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewDataTableAdapter query(
      org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewFilter aFilterCondition, 
      org.r3.db.PersistenceConfigInfo pcfg)
  {
      return query(aFilterCondition, pcfg, "1", -1, -1, false); 
  }  
}
  
