//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//


package org.r3.db.sailevent.appcrewmemberview;

import java.util.List;
import java.util.ArrayList;

public class SailApplicationCrewMemberViewFilter{
    protected String orderByClause;
    protected String  groupByClause;
    protected boolean distinct;
    protected int     limitFetch;
    
    protected List<org.r3.db.utils.Criteria> oredCriteria;

    public SailApplicationCrewMemberViewFilter() 
    {
        oredCriteria = new ArrayList<org.r3.db.utils.Criteria>();
        limitFetch = 0;
        groupByClause = null;
    }
    
    public String getGroupByClause()
	  {
	  	return groupByClause;
	  }
    
	  public void setGroupByClause(String groupByClause)
	  {
	  	this.groupByClause = groupByClause;
	  }
	
	  public boolean isGroupBy(String aColumnName)
	  {
	  	return groupByClause != null && groupByClause.indexOf(aColumnName) >= 0;
	  }
	
    public void setOrderByClause(String orderByClause) 
    {
        this.orderByClause = orderByClause;
    }
    
    public String getOrderByClause() 
    {
        return orderByClause;
    }

    public int getLimitFetch()
  	{
		   return limitFetch;
	  }

	  public void setLimitFetch(int limitFetch)
	  {
		  this.limitFetch = limitFetch;
	  }

    public void setDistinct(boolean distinct) 
    {
        this.distinct = distinct;
    }

    public boolean isDistinct() 
    {
        return distinct;
    }

    public List<org.r3.db.utils.Criteria> getOredCriteria() 
    {
        return oredCriteria;
    }

    public void or(org.r3.db.utils.Criteria criteria) 
    {
        oredCriteria.add(criteria);
    }

    public SailApplicationCrewMemberViewCriteria or() 
    {
        SailApplicationCrewMemberViewCriteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public SailApplicationCrewMemberViewCriteria createCriteria() 
    {
        SailApplicationCrewMemberViewCriteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected SailApplicationCrewMemberViewCriteria createCriteriaInternal() 
    {
        SailApplicationCrewMemberViewCriteria criteria = new SailApplicationCrewMemberViewCriteria();
        return criteria;
    }

    public void clear() 
    {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public static abstract class SailApplicationCrewMemberViewCriteriaBase extends org.r3.db.utils.Criteria
    {
        
        public SailApplicationCrewMemberViewCriteria andCrewmemberidIsNull() {
            addCriterion("crewmemberid is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberidIsNotNull() {
            addCriterion("crewmemberid is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberidEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberid =", value, "crewmemberid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberidNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberid <>", value, "crewmemberid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberidGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberid >", value, "crewmemberid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberidGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberid >=", value, "crewmemberid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberidLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberid <", value, "crewmemberid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberidLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberid <=", value, "crewmemberid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberidLike(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberid like ", value, "crewmemberid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberidNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberid not like ", value, "crewmemberid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberidIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("crewmemberid in ", value, "crewmemberid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberidNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("crewmemberid not in ", value, "crewmemberid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberidBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("crewmemberid between ", value1, value2, "crewmemberid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberidNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("crewmemberid not between ", value1, value2, "crewmemberid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andEventidIsNull() {
            addCriterion("eventid is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andEventidIsNotNull() {
            addCriterion("eventid is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andEventidEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("eventid =", value, "eventid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andEventidNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("eventid <>", value, "eventid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andEventidGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("eventid >", value, "eventid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andEventidGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("eventid >=", value, "eventid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andEventidLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("eventid <", value, "eventid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andEventidLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("eventid <=", value, "eventid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andEventidLike(java.lang.String value) {
            if (value != null)
              addCriterion("eventid like ", value, "eventid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andEventidNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("eventid not like ", value, "eventid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andEventidIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("eventid in ", value, "eventid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andEventidNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("eventid not in ", value, "eventid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andEventidBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("eventid between ", value1, value2, "eventid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andEventidNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("eventid not between ", value1, value2, "eventid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andApplicationidIsNull() {
            addCriterion("applicationid is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andApplicationidIsNotNull() {
            addCriterion("applicationid is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andApplicationidEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("applicationid =", value, "applicationid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andApplicationidNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("applicationid <>", value, "applicationid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andApplicationidGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("applicationid >", value, "applicationid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andApplicationidGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("applicationid >=", value, "applicationid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andApplicationidLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("applicationid <", value, "applicationid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andApplicationidLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("applicationid <=", value, "applicationid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andApplicationidLike(java.lang.String value) {
            if (value != null)
              addCriterion("applicationid like ", value, "applicationid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andApplicationidNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("applicationid not like ", value, "applicationid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andApplicationidIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("applicationid in ", value, "applicationid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andApplicationidNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("applicationid not in ", value, "applicationid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andApplicationidBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("applicationid between ", value1, value2, "applicationid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andApplicationidNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("applicationid not between ", value1, value2, "applicationid");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andCardnumberIsNull() {
            addCriterion("cardnumber is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberIsNotNull() {
            addCriterion("cardnumber is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumber =", value, "cardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumber <>", value, "cardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumber >", value, "cardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumber >=", value, "cardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumber <", value, "cardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumber <=", value, "cardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberLike(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumber like ", value, "cardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumber not like ", value, "cardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("cardnumber in ", value, "cardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("cardnumber not in ", value, "cardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("cardnumber between ", value1, value2, "cardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("cardnumber not between ", value1, value2, "cardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andCrewmembernameIsNull() {
            addCriterion("crewmembername is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmembernameIsNotNull() {
            addCriterion("crewmembername is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmembernameEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("crewmembername =", value, "crewmembername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmembernameNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("crewmembername <>", value, "crewmembername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmembernameGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("crewmembername >", value, "crewmembername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmembernameGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("crewmembername >=", value, "crewmembername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmembernameLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("crewmembername <", value, "crewmembername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmembernameLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("crewmembername <=", value, "crewmembername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmembernameLike(java.lang.String value) {
            if (value != null)
              addCriterion("crewmembername like ", value, "crewmembername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmembernameNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("crewmembername not like ", value, "crewmembername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmembernameIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("crewmembername in ", value, "crewmembername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmembernameNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("crewmembername not in ", value, "crewmembername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmembernameBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("crewmembername between ", value1, value2, "crewmembername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmembernameNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("crewmembername not between ", value1, value2, "crewmembername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andWeightIsNull() {
            addCriterion("weight is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andWeightEqualTo(java.lang.Float value) {
            if (value != null)
              addCriterion("weight =", value, "weight");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andWeightNotEqualTo(java.lang.Float value) {
            if (value != null)
              addCriterion("weight <>", value, "weight");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andWeightGreaterThan(java.lang.Float value) {
            if (value != null)
              addCriterion("weight >", value, "weight");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andWeightGreaterThanOrEqualTo(java.lang.Float value) {
            if (value != null)
              addCriterion("weight >=", value, "weight");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andWeightLessThan(java.lang.Float value) {
            if (value != null)
              addCriterion("weight <", value, "weight");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andWeightLessThanOrEqualTo(java.lang.Float value) {
            if (value != null)
              addCriterion("weight <=", value, "weight");
            return (SailApplicationCrewMemberViewCriteria) this;
        }

        
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeIsNull() {
            addCriterion("crewmemberrolecode is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeIsNotNull() {
            addCriterion("crewmemberrolecode is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberrolecode =", value, "crewmemberrolecode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberrolecode <>", value, "crewmemberrolecode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberrolecode >", value, "crewmemberrolecode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberrolecode >=", value, "crewmemberrolecode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberrolecode <", value, "crewmemberrolecode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberrolecode <=", value, "crewmemberrolecode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeLike(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberrolecode like ", value, "crewmemberrolecode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("crewmemberrolecode not like ", value, "crewmemberrolecode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("crewmemberrolecode in ", value, "crewmemberrolecode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("crewmemberrolecode not in ", value, "crewmemberrolecode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("crewmemberrolecode between ", value1, value2, "crewmemberrolecode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCrewmemberrolecodeNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("crewmemberrolecode not between ", value1, value2, "crewmemberrolecode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeIsNull() {
            addCriterion("memberstatuscode is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeIsNotNull() {
            addCriterion("memberstatuscode is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("memberstatuscode =", value, "memberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("memberstatuscode <>", value, "memberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("memberstatuscode >", value, "memberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("memberstatuscode >=", value, "memberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("memberstatuscode <", value, "memberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("memberstatuscode <=", value, "memberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeLike(java.lang.String value) {
            if (value != null)
              addCriterion("memberstatuscode like ", value, "memberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("memberstatuscode not like ", value, "memberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("memberstatuscode in ", value, "memberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("memberstatuscode not in ", value, "memberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("memberstatuscode between ", value1, value2, "memberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMemberstatuscodeNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("memberstatuscode not between ", value1, value2, "memberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andCreatetimestampIsNull() {
            addCriterion("createtimestamp is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCreatetimestampIsNotNull() {
            addCriterion("createtimestamp is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCreatetimestampEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("createtimestamp =", value, "createtimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCreatetimestampNotEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("createtimestamp <>", value, "createtimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCreatetimestampGreaterThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("createtimestamp >", value, "createtimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCreatetimestampGreaterThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("createtimestamp >=", value, "createtimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCreatetimestampLessThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("createtimestamp <", value, "createtimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCreatetimestampLessThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("createtimestamp <=", value, "createtimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }

        
        public SailApplicationCrewMemberViewCriteria andDeletetimestampIsNull() {
            addCriterion("deletetimestamp is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andDeletetimestampIsNotNull() {
            addCriterion("deletetimestamp is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andDeletetimestampEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("deletetimestamp =", value, "deletetimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andDeletetimestampNotEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("deletetimestamp <>", value, "deletetimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andDeletetimestampGreaterThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("deletetimestamp >", value, "deletetimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andDeletetimestampGreaterThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("deletetimestamp >=", value, "deletetimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andDeletetimestampLessThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("deletetimestamp <", value, "deletetimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andDeletetimestampLessThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("deletetimestamp <=", value, "deletetimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }

        
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberIsNull() {
            addCriterion("checkcardnumber is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberIsNotNull() {
            addCriterion("checkcardnumber is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("checkcardnumber =", value, "checkcardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("checkcardnumber <>", value, "checkcardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("checkcardnumber >", value, "checkcardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("checkcardnumber >=", value, "checkcardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("checkcardnumber <", value, "checkcardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("checkcardnumber <=", value, "checkcardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberLike(java.lang.String value) {
            if (value != null)
              addCriterion("checkcardnumber like ", value, "checkcardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("checkcardnumber not like ", value, "checkcardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("checkcardnumber in ", value, "checkcardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("checkcardnumber not in ", value, "checkcardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("checkcardnumber between ", value1, value2, "checkcardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumberNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("checkcardnumber not between ", value1, value2, "checkcardnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andCheckcardnumber_tsIsNull() {
            addCriterion("checkcardnumber_ts is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumber_tsIsNotNull() {
            addCriterion("checkcardnumber_ts is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumber_tsEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("checkcardnumber_ts =", value, "checkcardnumber_ts");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumber_tsNotEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("checkcardnumber_ts <>", value, "checkcardnumber_ts");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumber_tsGreaterThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("checkcardnumber_ts >", value, "checkcardnumber_ts");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumber_tsGreaterThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("checkcardnumber_ts >=", value, "checkcardnumber_ts");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumber_tsLessThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("checkcardnumber_ts <", value, "checkcardnumber_ts");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCheckcardnumber_tsLessThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("checkcardnumber_ts <=", value, "checkcardnumber_ts");
            return (SailApplicationCrewMemberViewCriteria) this;
        }

        
        public SailApplicationCrewMemberViewCriteria andRecstatusIsNull() {
            addCriterion("recstatus is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRecstatusIsNotNull() {
            addCriterion("recstatus is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRecstatusEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("recstatus =", value, "recstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRecstatusNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("recstatus <>", value, "recstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRecstatusGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("recstatus >", value, "recstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRecstatusGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("recstatus >=", value, "recstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRecstatusLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("recstatus <", value, "recstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRecstatusLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("recstatus <=", value, "recstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRecstatusLike(java.lang.String value) {
            if (value != null)
              addCriterion("recstatus like ", value, "recstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRecstatusNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("recstatus not like ", value, "recstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRecstatusIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("recstatus in ", value, "recstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRecstatusNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("recstatus not in ", value, "recstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRecstatusBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("recstatus between ", value1, value2, "recstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRecstatusNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("recstatus not between ", value1, value2, "recstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andRectimestampIsNull() {
            addCriterion("rectimestamp is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRectimestampIsNotNull() {
            addCriterion("rectimestamp is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRectimestampEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("rectimestamp =", value, "rectimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRectimestampNotEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("rectimestamp <>", value, "rectimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRectimestampGreaterThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("rectimestamp >", value, "rectimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRectimestampGreaterThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("rectimestamp >=", value, "rectimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRectimestampLessThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("rectimestamp <", value, "rectimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRectimestampLessThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("rectimestamp <=", value, "rectimestamp");
            return (SailApplicationCrewMemberViewCriteria) this;
        }

        
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeIsNull() {
            addCriterion("cardnumberstatuscode is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeIsNotNull() {
            addCriterion("cardnumberstatuscode is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumberstatuscode =", value, "cardnumberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumberstatuscode <>", value, "cardnumberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumberstatuscode >", value, "cardnumberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumberstatuscode >=", value, "cardnumberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumberstatuscode <", value, "cardnumberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumberstatuscode <=", value, "cardnumberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeLike(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumberstatuscode like ", value, "cardnumberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("cardnumberstatuscode not like ", value, "cardnumberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("cardnumberstatuscode in ", value, "cardnumberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("cardnumberstatuscode not in ", value, "cardnumberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("cardnumberstatuscode between ", value1, value2, "cardnumberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardnumberstatuscodeNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("cardnumberstatuscode not between ", value1, value2, "cardnumberstatuscode");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andYachtclubIsNull() {
            addCriterion("yachtclub is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtclubIsNotNull() {
            addCriterion("yachtclub is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtclubEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("yachtclub =", value, "yachtclub");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtclubNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("yachtclub <>", value, "yachtclub");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtclubGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("yachtclub >", value, "yachtclub");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtclubGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("yachtclub >=", value, "yachtclub");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtclubLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("yachtclub <", value, "yachtclub");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtclubLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("yachtclub <=", value, "yachtclub");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtclubLike(java.lang.String value) {
            if (value != null)
              addCriterion("yachtclub like ", value, "yachtclub");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtclubNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("yachtclub not like ", value, "yachtclub");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtclubIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("yachtclub in ", value, "yachtclub");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtclubNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("yachtclub not in ", value, "yachtclub");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtclubBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("yachtclub between ", value1, value2, "yachtclub");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtclubNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("yachtclub not between ", value1, value2, "yachtclub");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andCardholdernameIsNull() {
            addCriterion("cardholdername is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholdernameIsNotNull() {
            addCriterion("cardholdername is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholdernameEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardholdername =", value, "cardholdername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholdernameNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardholdername <>", value, "cardholdername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholdernameGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("cardholdername >", value, "cardholdername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholdernameGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardholdername >=", value, "cardholdername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholdernameLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("cardholdername <", value, "cardholdername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholdernameLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardholdername <=", value, "cardholdername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholdernameLike(java.lang.String value) {
            if (value != null)
              addCriterion("cardholdername like ", value, "cardholdername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholdernameNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("cardholdername not like ", value, "cardholdername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholdernameIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("cardholdername in ", value, "cardholdername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholdernameNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("cardholdername not in ", value, "cardholdername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholdernameBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("cardholdername between ", value1, value2, "cardholdername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholdernameNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("cardholdername not between ", value1, value2, "cardholdername");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameIsNull() {
            addCriterion("cardholderlastname is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameIsNotNull() {
            addCriterion("cardholderlastname is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardholderlastname =", value, "cardholderlastname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardholderlastname <>", value, "cardholderlastname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("cardholderlastname >", value, "cardholderlastname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardholderlastname >=", value, "cardholderlastname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("cardholderlastname <", value, "cardholderlastname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("cardholderlastname <=", value, "cardholderlastname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameLike(java.lang.String value) {
            if (value != null)
              addCriterion("cardholderlastname like ", value, "cardholderlastname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("cardholderlastname not like ", value, "cardholderlastname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("cardholderlastname in ", value, "cardholderlastname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("cardholderlastname not in ", value, "cardholderlastname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("cardholderlastname between ", value1, value2, "cardholderlastname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardholderlastnameNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("cardholderlastname not between ", value1, value2, "cardholderlastname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andMedexamexpirationdateIsNull() {
            addCriterion("medexamexpirationdate is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMedexamexpirationdateIsNotNull() {
            addCriterion("medexamexpirationdate is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMedexamexpirationdateEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("medexamexpirationdate =", value, "medexamexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMedexamexpirationdateNotEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("medexamexpirationdate <>", value, "medexamexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMedexamexpirationdateGreaterThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("medexamexpirationdate >", value, "medexamexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMedexamexpirationdateGreaterThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("medexamexpirationdate >=", value, "medexamexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMedexamexpirationdateLessThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("medexamexpirationdate <", value, "medexamexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andMedexamexpirationdateLessThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("medexamexpirationdate <=", value, "medexamexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }

        
        public SailApplicationCrewMemberViewCriteria andCardexpirationdateIsNull() {
            addCriterion("cardexpirationdate is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardexpirationdateIsNotNull() {
            addCriterion("cardexpirationdate is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardexpirationdateEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("cardexpirationdate =", value, "cardexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardexpirationdateNotEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("cardexpirationdate <>", value, "cardexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardexpirationdateGreaterThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("cardexpirationdate >", value, "cardexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardexpirationdateGreaterThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("cardexpirationdate >=", value, "cardexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardexpirationdateLessThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("cardexpirationdate <", value, "cardexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCardexpirationdateLessThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("cardexpirationdate <=", value, "cardexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }

        
        public SailApplicationCrewMemberViewCriteria andRenewaldateIsNull() {
            addCriterion("renewaldate is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRenewaldateIsNotNull() {
            addCriterion("renewaldate is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRenewaldateEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("renewaldate =", value, "renewaldate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRenewaldateNotEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("renewaldate <>", value, "renewaldate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRenewaldateGreaterThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("renewaldate >", value, "renewaldate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRenewaldateGreaterThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("renewaldate >=", value, "renewaldate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRenewaldateLessThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("renewaldate <", value, "renewaldate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andRenewaldateLessThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("renewaldate <=", value, "renewaldate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }

        
        public SailApplicationCrewMemberViewCriteria andGeneralcardexpirationdateIsNull() {
            addCriterion("generalcardexpirationdate is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andGeneralcardexpirationdateIsNotNull() {
            addCriterion("generalcardexpirationdate is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andGeneralcardexpirationdateEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("generalcardexpirationdate =", value, "generalcardexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andGeneralcardexpirationdateNotEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("generalcardexpirationdate <>", value, "generalcardexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andGeneralcardexpirationdateGreaterThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("generalcardexpirationdate >", value, "generalcardexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andGeneralcardexpirationdateGreaterThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("generalcardexpirationdate >=", value, "generalcardexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andGeneralcardexpirationdateLessThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("generalcardexpirationdate <", value, "generalcardexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andGeneralcardexpirationdateLessThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("generalcardexpirationdate <=", value, "generalcardexpirationdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }

        
        public SailApplicationCrewMemberViewCriteria andSystemcheckdateIsNull() {
            addCriterion("systemcheckdate is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSystemcheckdateIsNotNull() {
            addCriterion("systemcheckdate is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSystemcheckdateEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("systemcheckdate =", value, "systemcheckdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSystemcheckdateNotEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("systemcheckdate <>", value, "systemcheckdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSystemcheckdateGreaterThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("systemcheckdate >", value, "systemcheckdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSystemcheckdateGreaterThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("systemcheckdate >=", value, "systemcheckdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSystemcheckdateLessThan(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("systemcheckdate <", value, "systemcheckdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSystemcheckdateLessThanOrEqualTo(java.sql.Timestamp value) {
            if (value != null)
              addCriterion("systemcheckdate <=", value, "systemcheckdate");
            return (SailApplicationCrewMemberViewCriteria) this;
        }

        
        public SailApplicationCrewMemberViewCriteria andSailnumberIsNull() {
            addCriterion("sailnumber is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSailnumberIsNotNull() {
            addCriterion("sailnumber is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSailnumberEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("sailnumber =", value, "sailnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSailnumberNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("sailnumber <>", value, "sailnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSailnumberGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("sailnumber >", value, "sailnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSailnumberGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("sailnumber >=", value, "sailnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSailnumberLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("sailnumber <", value, "sailnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSailnumberLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("sailnumber <=", value, "sailnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSailnumberLike(java.lang.String value) {
            if (value != null)
              addCriterion("sailnumber like ", value, "sailnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSailnumberNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("sailnumber not like ", value, "sailnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSailnumberIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("sailnumber in ", value, "sailnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSailnumberNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("sailnumber not in ", value, "sailnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSailnumberBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("sailnumber between ", value1, value2, "sailnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andSailnumberNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("sailnumber not between ", value1, value2, "sailnumber");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andYachtnameIsNull() {
            addCriterion("yachtname is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtnameIsNotNull() {
            addCriterion("yachtname is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtnameEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("yachtname =", value, "yachtname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtnameNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("yachtname <>", value, "yachtname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtnameGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("yachtname >", value, "yachtname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtnameGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("yachtname >=", value, "yachtname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtnameLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("yachtname <", value, "yachtname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtnameLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("yachtname <=", value, "yachtname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtnameLike(java.lang.String value) {
            if (value != null)
              addCriterion("yachtname like ", value, "yachtname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtnameNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("yachtname not like ", value, "yachtname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtnameIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("yachtname in ", value, "yachtname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtnameNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("yachtname not in ", value, "yachtname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtnameBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("yachtname between ", value1, value2, "yachtname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andYachtnameNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("yachtname not between ", value1, value2, "yachtname");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andCompletionstatusIsNull() {
            addCriterion("completionstatus is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCompletionstatusIsNotNull() {
            addCriterion("completionstatus is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCompletionstatusEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("completionstatus =", value, "completionstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCompletionstatusNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("completionstatus <>", value, "completionstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCompletionstatusGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("completionstatus >", value, "completionstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCompletionstatusGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("completionstatus >=", value, "completionstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCompletionstatusLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("completionstatus <", value, "completionstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCompletionstatusLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("completionstatus <=", value, "completionstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCompletionstatusLike(java.lang.String value) {
            if (value != null)
              addCriterion("completionstatus like ", value, "completionstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCompletionstatusNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("completionstatus not like ", value, "completionstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCompletionstatusIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("completionstatus in ", value, "completionstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCompletionstatusNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("completionstatus not in ", value, "completionstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCompletionstatusBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("completionstatus between ", value1, value2, "completionstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andCompletionstatusNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("completionstatus not between ", value1, value2, "completionstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        
        public SailApplicationCrewMemberViewCriteria andVerificationstatusIsNull() {
            addCriterion("verificationstatus is null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andVerificationstatusIsNotNull() {
            addCriterion("verificationstatus is not null");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andVerificationstatusEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("verificationstatus =", value, "verificationstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andVerificationstatusNotEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("verificationstatus <>", value, "verificationstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andVerificationstatusGreaterThan(java.lang.String value) {
            if (value != null)
              addCriterion("verificationstatus >", value, "verificationstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andVerificationstatusGreaterThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("verificationstatus >=", value, "verificationstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andVerificationstatusLessThan(java.lang.String value) {
            if (value != null)
              addCriterion("verificationstatus <", value, "verificationstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andVerificationstatusLessThanOrEqualTo(java.lang.String value) {
            if (value != null)
              addCriterion("verificationstatus <=", value, "verificationstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andVerificationstatusLike(java.lang.String value) {
            if (value != null)
              addCriterion("verificationstatus like ", value, "verificationstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andVerificationstatusNotLike(java.lang.String value) {
            if (value != null)
              addCriterion("verificationstatus not like ", value, "verificationstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andVerificationstatusIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
              addCriterion("verificationstatus in ", value, "verificationstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andVerificationstatusNotIn(java.util.List<java.lang.String> value) {
            if (value != null && value.size() > 0)
               addCriterion("verificationstatus not in ", value, "verificationstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andVerificationstatusBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("verificationstatus between ", value1, value2, "verificationstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        public SailApplicationCrewMemberViewCriteria andVerificationstatusNotBetween(java.lang.String value1, java.lang.String value2) {
            if (value1 != null && value2 != null)
              addCriterion("verificationstatus not between ", value1, value2, "verificationstatus");
            return (SailApplicationCrewMemberViewCriteria) this;
        }
        

    }
    
}

