//
// generated by jGAMe Software - GPA Gruppo Progetti Avanzati s.r.l. 2016-2017
//
//
// README Section
//


package org.r3.db.sailevent.appcrewmemberview;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SailApplicationCrewMemberViewMapper{    
  List<org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewDTO> select(
            @Param("filter") org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewFilter filterCondition, 
            @Param("pcfg")   org.r3.db.PersistenceConfigInfo pcfg,
            RowBounds aRowBounds);
            
  int count(@Param("filter") org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewFilter aFilterCondition,
            @Param("pcfg")   org.r3.db.PersistenceConfigInfo pcfg);

  List<org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewSummaryDTO> selectCrewReport(
		            @Param("filter") org.r3.db.sailevent.appcrewmemberview.SailApplicationCrewMemberViewFilter filterCondition, 
		            @Param("pcfg")   org.r3.db.PersistenceConfigInfo pcfg);            
}
  
